In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("dirty_cafe_sales.csv")

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df.shape

(10000, 8)

In [7]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [9]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
mean_value = df['Quantity'].mean()
df['Quantity'] = df['Quantity'].fillna(mean_value).astype(int)

In [10]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [11]:
for col in ['Total Spent', 'Price Per Unit']:
    df[col] = pd.to_numeric(df[col], errors='coerce')       # convert to numeric
    mean_value = df[col].mean()                              # calculate mean
    df[col].fillna(mean_value, inplace=True)                 # fill NaNs with mean
    df[col] = df[col].astype(float)                          # ensure float type

In [12]:
for col in ['Payment Method', 'Location']:
    mode_value = df[col].mode()[0]      # get the most frequent value
    df[col].fillna(mode_value, inplace=True)  # fill missing values with mode

In [13]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11

In [14]:
df.isnull().sum()

Transaction ID        0
Item                333
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    159
dtype: int64

In [15]:
mode_item = df['Item'].mode()[0]
df['Item'].fillna(mode_item, inplace=True)
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
mode_date = df['Transaction Date'].mode()[0]
df['Transaction Date'].fillna(mode_date, inplace=True)
for col in ['Payment Method', 'Location']:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)       # fill NaN
    df[col].replace('UNKNOWN', mode_value, inplace=True)  # replace 'UNKNOWN'

In [16]:
print(df.isnull().sum())
print("Count of 'UNKNOWN' in Location column:", (df['Location'] == 'UNKNOWN').sum())
display(df.head())

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64
Count of 'UNKNOWN' in Location column: 0

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11